### Without Gateway

http://localhost:9002/value

### With Gateway

http://localhost:9000/aggregator/value

### With Token & Gateway

http://localhost:9000/aggregator/api/payments
Authorization: eyJhbGciOiJSUzI1NiJ9.eyJpZCI6MiwiZXhwIjoxNjMzOTEyODUwLCJpYXQiOjE2MzM5MDkyNTB9.UvawIltNjgpbuHCnS76dNr-j3RPHlzFoNcYqY8XMxa4fh9vpJ9bh8hKbiDS4pHI1WrUlc4wS6vMqY75Y7T3TM_uO0n8IUFW-wrW8lNePJltEOEHP7H1LLhd-T8SjkSv_-tmg0VAfAAuF6k63QZ9KynHMflK2Ka4w825SXneQj_6kTYXJHS7ljp6Ge41mBb_f5SrFQvl6rHNVZgBDCLgLWKaRC_WBSI0LPr0SNFNzoWqklHxfAS193YEJVehcD5WC_IFAWBIpwMUN6pi-rq2Oci847zpJGbUohE-9lGQh1orsszASgjPU5XKJZ76t8ESoyfPFSmlYZk1XvdTRDMGoEg

###
GET http://localhost:9002/api/payments
###

POST http://localhost:9000/producer/api/payments
Authorization: eyJhbGciOiJSUzI1NiJ9.eyJpZCI6MiwiZXhwIjoxNjMzOTEyODUwLCJpYXQiOjE2MzM5MDkyNTB9.UvawIltNjgpbuHCnS76dNr-j3RPHlzFoNcYqY8XMxa4fh9vpJ9bh8hKbiDS4pHI1WrUlc4wS6vMqY75Y7T3TM_uO0n8IUFW-wrW8lNePJltEOEHP7H1LLhd-T8SjkSv_-tmg0VAfAAuF6k63QZ9KynHMflK2Ka4w825SXneQj_6kTYXJHS7ljp6Ge41mBb_f5SrFQvl6rHNVZgBDCLgLWKaRC_WBSI0LPr0SNFNzoWqklHxfAS193YEJVehcD5WC_IFAWBIpwMUN6pi-rq2Oci847zpJGbUohE-9lGQh1orsszASgjPU5XKJZ76t8ESoyfPFSmlYZk1XvdTRDMGoEg
Content-Type: application/json

{
  "amount": 765,
  "cardNumber": 5212223222337122,
  "comment": "asd"
}

###
POST http://localhost:54849/api/user
Content-Type: application/json

{
  "id": 2,
  "username": "dima"
}
