### Without Gateway

http://localhost:9002/value

### With Gateway

http://localhost:9000/aggregator/value

### With Token & Gateway

http://localhost:9000/aggregator/api/payments
Authorization: eyJhbGciOiJSUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsImlkIjozLCJleHAiOjE2MzM5MTk2MTcsImlhdCI6MTYzMzkxNjAxN30.DdbYTtBOonPi5KG7cR8ZrJz5UxQ6PXD7Jd3Xd0BbM61aPtH2HzlcX9zrUrwnNXqAoFtBE-xzm00voFD2zA3Fwrp7qePYFNEzgAwQ6eTgGPa4mtV7VZ6qsZ7I7Ma4gdIgvIvLXjoUarfEhtgaYFzkjhRZhaInZPHrwbx1o3b55ybfHARhnItFTvEAAYzr5qJZAUAsRiLb6n4OUYUYVus892u2jL_ErCeTrX6m7DiCi8vd1_1_OONBLMgn4EQPeh75n1dFLToJoGvDS6-V2T2u-JhQtsDJmvJOM5u9oA6WZ3zc-t-tE_6MNUaoY7i2naDR4e9R1K2F4azt-_KLWZJNyA
###
GET http://localhost:9002/api/payments
###

POST http://localhost:9000/producer/api/payments
Authorization: eyJhbGciOiJSUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOjIsImV4cCI6MTYzMzkxOTU4NiwiaWF0IjoxNjMzOTE1OTg2fQ.SigXVtlEGYd5NGmRLt7pIoZQNNSAJd66KJFx6CFzvlQHXHEgAKDLw61_vH6N_ZMdWXfnB1dmajvbAr8qHuTOcC5bNM-CXf7Z46OnZRdZPHzJfDGNgEyaU1F8fxmvCxhq87Fte0L3HtU7E0VW7Ih3TxsSNFWZ9ocdSK8tMy5Xfze42x6uuFLtVgk2q5Hl4kCnfCewLzA1ex-UNgQve0IkvW5Wd5d5JWcp-lf7Z2_LezmdeGOJ8pAhOefHMORTSPTIKPlIKgUV1S6jWPs_S0cLJbbcJDfO3PRDLcuueJEgxVqyCqWvehshToscVLwB01ALEDqe0zNJoBppR8GRjOAcEw
Content-Type: application/json

{
  "amount": 444,
  "cardNumber": 5212223222337122,
  "comment": "asd"
}

###
POST http://localhost:57017/api/user
Content-Type: application/json

{
  "id": 3,
  "username": "egor",
  "role": "ROLE_ADMIN"
}

###
http://localhost:9000/aggregator/api/payments
Authorization: eyJhbGciOiJSUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsImlkIjoxLCJleHAiOjE2MzM5MTkzNTUsImlhdCI6MTYzMzkxNTc1NX0.G7zOSTojT5py7CZHz36sr1HGjPqaMN2yy23I8FmzG34MRtG-drRrlG87S6dCHGemOla0kqP4gArmoyNHqcIds598cOFtKVx0fvRjE-SaRjhaskffUQLsncfVMkt90OVog0tdZZFI6-_fQkbfG4mpCgl09y76tWq6GAK4jsPaRrDr9FG66_3xD7-u6BNZEb4_RC0aLl-_je64FPiC9SOSnhdWioF3lDDSOOJDilJlAjbQgfG_a4kzTjfk-c_-7Ms8-YDHw-wfypmvkX76qhIu6lQIePNao6PJUM01jmKUQCn08PL9paVEFHyKMBRRK-xBqeq-RuWxMJ2drUwuv7lUpQ